env:
  DOCKER_IMAGE_NAME: client-svc
  DOCKER_REGISTRY: public.ecr.aws
name: "Client Build and Terraform Deployment"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "hello-world-client/**"
  pull_request:
    branches: [main]
    paths:
      - "hello-world-client/**"
jobs:
  build:
    defaults:
      run:
        working-directory: ./hello-world-client
    name: Maven Build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app.jar
          path: hello-world-client/target/hello-world-client-0.0.1.jar
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon Public ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app.jar
      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
      - name: Build Docker image
        uses: docker/build-push-action@v6
        env:
          IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
        with:
          context: ./hello-world-client
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY}}/l3s1l9f4/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_REGISTRY}}/l3s1l9f4/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          provenance: false
  terraform:
    defaults:
      run:
        working-directory: ./hello-world-client/terraform
    needs: [build]
    name:  Build Terraform - Env ${{ matrix.environment }}
    runs-on: [ubuntu-latest]
    strategy:
      max-parallel: 1
      matrix:
        include:
            - environment: dev
    env:
      aws_secret_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_container_version: "latest"
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - uses: hashicorp/setup-terraform@v1
      with:
          terraform_wrapper: false
    - name: Terraform Init
      id: init
      run: |
        rm -rf .terraform
        terraform init -backend-config=${{ matrix.environment }}/backend.tfvars -upgrade=true -no-color -input=false
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -var-file=${{ matrix.environment }}/terraform.tfvars -no-color
    - name: Terraform apply
      if: github.ref == 'refs/heads/main'
      id: apply
      run: |
        terraform apply -var-file=${{ matrix.environment }}/terraform.tfvars -no-color --auto-approve=true
